# SignalBox - cmake/build-id.cmake
#
# NOT vendored from obs-plugintemplate (unlike cmake/common and cmake/windows -
# see CMakeLists.txt's header). This one is ours.
#
# Run in script mode (cmake -P) to write a header defining SIGNALBOX_BUILD_ID
# as the commit the build came from, with a trailing "+" when the working tree
# has uncommitted changes.
#
# WHY THIS IS A SCRIPT AND NOT JUST A FEW LINES IN CMakeLists.txt: because it
# has to run on every BUILD, not every CONFIGURE. The first version of this
# computed the id inline during configure, which meant it was captured once and
# then never updated - CMake does not re-configure just because someone
# committed. The result was a DLL stamped with the previous commit, marked
# dirty, while the tree was clean and a commit ahead. A build id that is merely
# absent is a small gap; one that confidently reports the wrong commit is worse
# than having none at all, because it is trusted. Caught by checking the string
# actually embedded in the binary rather than the value CMake printed.
#
# Expects: SRC_DIR (repo root), OUT_FILE (header to write).

find_package(Git QUIET)

set(_build_id "unknown")
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE _sha
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _sha_result)

  if(_sha_result EQUAL 0 AND _sha)
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain
      WORKING_DIRECTORY "${SRC_DIR}"
      OUTPUT_VARIABLE _dirty
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)

    if(_dirty)
      set(_build_id "${_sha}+")
    else()
      set(_build_id "${_sha}")
    endif()
  endif()
endif()

set(_content "// Generated by cmake/build-id.cmake on every build - do not edit.\n#pragma once\n#define SIGNALBOX_BUILD_ID \"${_build_id}\"\n")

# Rewrite ONLY on a real change. This header is included by translation units
# that would otherwise recompile on every single build, turning a no-op build
# into a full one.
set(_existing "")
if(EXISTS "${OUT_FILE}")
  file(READ "${OUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
  file(WRITE "${OUT_FILE}" "${_content}")
  message(STATUS "SignalBox build id: ${_build_id}")
endif()
